# Generated by Django 3.1.2 on 2020-11-12 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('core_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('age_range_start', models.CharField(max_length=12)),
                ('age_range_end', models.CharField(max_length=12)),
                ('researchers', models.JSONField(null=True)),
                ('isotopes', models.JSONField(null=True)),
                ('parameters', models.JSONField(null=True)),
            ],
        ),
    ]
