# Generated by Django 3.1.2 on 2020-12-19 20:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isotope',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('type', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Za-z\\-\\.]+$', 'Only alphabet characters are allowed.')])),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('researcher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z\\-\\.]+$', 'Only alphabet characters are allowed.')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\-\\.]+$', 'Only alphabet characters are allowed.')])),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document_file', models.FileField(upload_to='document/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=50)),
                ('core_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('age_range_start', models.CharField(max_length=12)),
                ('age_range_end', models.CharField(max_length=12)),
                ('isotopes', models.ManyToManyField(to='cicl.Isotope')),
                ('parameters', models.ManyToManyField(to='cicl.Parameter')),
                ('researchers', models.ManyToManyField(to='cicl.Researcher')),
            ],
            options={
                'ordering': ['core_name'],
            },
        ),
    ]
